// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlbAlU08u2PJJd3Cqeed6bB-_-8Jqnt40',
    appId: '1:36441603219:web:4b8f87afafd929b8e12166',
    messagingSenderId: '36441603219',
    projectId: 'bingus_bongus-64',
    authDomain: 'bingus_bongus-64.firebaseapp.com',
    storageBucket: 'bingus_bongus-64.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbmdH5yRdS_6i3HHEdHAdsYnBX74ASEAs',
    appId: '1:36441603219:android:e6523647c8c5e7dee12166',
    messagingSenderId: '36441603219',
    projectId: 'bingus_bongus-64',
    storageBucket: 'bingus_bongus-64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAStnWOAzIrYmfiDeqpUsg872KYWxkC6Qs',
    appId: '1:36441603219:ios:f1b6de425172db77e12166',
    messagingSenderId: '36441603219',
    projectId: 'bingus_bongus-64',
    storageBucket: 'bingus_bongus-64.appspot.com',
    iosBundleId: 'com.example.baseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAStnWOAzIrYmfiDeqpUsg872KYWxkC6Qs',
    appId: '1:36441603219:ios:59b2c0f937c7db75e12166',
    messagingSenderId: '36441603219',
    projectId: 'bingus_bongus-64',
    storageBucket: 'bingus_bongus-64.appspot.com',
    iosBundleId: 'com.example.baseFlutter.RunnerTests',
  );
}
